### PR TITLE
SC-11678 add icons for PR decoration

### PR DESCRIPTION
**Pull request by bogdanakushnir**

### CODE REVIEW

**Review by ShaneFindley — APPROVED** [review]
Looks good to me, Greg mentioned putting the new content into a v3 folder. This could potentially help to isolate the changes.

**Review by gregaubert — COMMENTED** [review]
Is it on purpose that they are aligned on the bottom? and not in the center of the "frame"?

Also don't hesitate to pass the png images through https://tinypng.com/ to reduce the size as much as possible.
And the SVG images through https://jakearchibald.github.io/svgomg/ for the same purpose.

**Comment by gregaubert** [comment]
> Looks good to me, Greg mentioned putting the new content into a v3 folder. This could potentially help to isolate the changes.

If we are only adding content, there is no need for a new folder. Only if we want to delete or rename stuff that we need a new folder.

**Comment by bogdanakushnir** [comment]
> Is it on purpose that they are aligned on the bottom? and not in the center of the "frame"?
> 
> Also don't hesitate to pass the png images through https://tinypng.com/ to reduce the size as much as possible. And the SVG images through https://jakearchibald.github.io/svgomg/ for the same purpose.

I've just pushed icons with the reduced size, and as for the alignment - the icons were taken from the SQ code, as these changes were already done on their side.

**Review by gregaubert — APPROVED** [review]
Should be fine then!
Thanks for reducing the size!

**Comment by ShaneFindley** [comment]
> > Is it on purpose that they are aligned on the bottom? and not in the center of the "frame"?
> > Also don't hesitate to pass the png images through https://tinypng.com/ to reduce the size as much as possible. And the SVG images through https://jakearchibald.github.io/svgomg/ for the same purpose.
> 
> I've just pushed icons with the reduced size, and as for the alignment - the icons were taken from the SQ code, as these changes were already done on their side.

The padding on the top is due to alignment limitations in GH decorations.

**Pull request merged**
