### PR TITLE
SC-2620 Update duplication ratings icons

### PR DESCRIPTION
**Pull request by gregaubert**

### CODE REVIEW

**Comment by gregaubert** [comment]
@claire-villard-sonarsource Asking you to review since you are the last one who committed on this repo :)

**Review by claire-villard-sonarsource — APPROVED** [review]
Those new icons looks good, I don't see anything obvious, but I don't really know what I should check to validate a PR on that repo...

**Comment by gregaubert** [comment]
> Those new icons looks good, I don't see anything obvious, but I don't really know what I should check to validate a PR on that repo...

Honestly I have no idea either, especially since we will be able to see the new icons only once it's merged... I guess only thing to check is that I didn't forgot some place or files...

**Comment by claire-villard-sonarsource** [comment]
> Honestly I have no idea either, especially since we will be able to see the new icons only once it's merged... I guess only thing to check is that I didn't forgot some place or files...

I think all duplication icons are updated, their size match, and I suppose v1 is out of scope, so LGTM and see what happens ^^

**Pull request merged**
