### PR TITLE
NO-JIRA Update CODEOWNERS

### PR DESCRIPTION
**Pull request by anita-stanisz-sonarsource**

### CODE REVIEW

**Review by jacek-poreda-sonarsource — APPROVED** [review]

**Comment by jacek-poreda-sonarsource** [comment]
Is the target branch correct?

**Comment by anita-stanisz-sonarsource** [comment]
> Is the target branch correct?

It's the default and only one in this repo, I don't know why it has an unusual name...

**Comment by jacek-poreda-sonarsource** [comment]
Hmm, right!

**Comment by claire-villard-sonarsource** [comment]
> > Is the target branch correct?
> 
> It's the default and only one in this repo, I don't know why it has an unusual name...

If I may: I think we use (or used, not sure) Github Pages to publish those artifacts online. When it was released, I think I remember GitHub pages had a limitation and required a branch with a specific name to be able to publish.
This limitation was removed since then, and I guess the configuration of this repo was never changed.

**Pull request merged**
